# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4ced3a79c3d14324a3f8991dd1be14b9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3488a31a697848b0916aac188ebf9282 }}

    - name: Build and push container image to Docker hub
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4ced3a79c3d14324a3f8991dd1be14b9 }}/ecommerceapi:container_${{ github.sha }}
        file: ./EcommerceApi/Dockerfile
    

  Generate_sql_script:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
    
    - name: Install Maven
      run: |
        sudo apt-get install -y maven
    
    - name: Generate scripts
      run: mvn clean compile exec:java -Dexec.mainClass="your.package.App" # Replace "your.package.App" with your main class

    - name: Azure SQL Deploy 
      uses: Azure/sql-action@v2.2
      with:
          server-name: tcp:ecom-general-api.database.windows.net
          connection-string: ${{ secrets.DB_CONNECTION }}
          path: './sql/sql-script.sql'
  
  
  Deploy:
    runs-on: ubuntu-latest
    needs: Generate_sql_script
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ecom-general-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_babea2dfcdef442e888ffaa99a5aeea6 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_4ced3a79c3d14324a3f8991dd1be14b9 }}/ecommerceapi:container_${{ github.sha }}'
